config/routes.rb
Libapp::Application.routes.draw do
  get "/register", to: "readers#new", as: "register"
  get "/login", to: "sessions#new", as: "login"

  resources :readers
  resources :sessions

  root to: "home#index"
end

app/models/login.rb
class Login
  include ActiveAttr::BasicModel
  include ActiveAttr::MassAssignment
  attr_accessor :email, :password
end

app/models/reader.rb
class Reader < ActiveRecord::Base
  validates :email, presence: true
  validates :email, email: true
  validates :password, presence: true
  validates :email, uniqueness: true
  validates :password, confirmation: true
  attr_accessor :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  def new
    @reader = Reader.new
  end

  def create
    @reader = Reader.new(reader_params)
    if @reader.save
      redirect_to root_url, notice: "You registered"
    else
      flash.now[:error] = "Wrong parameters"
      render :new
    end
  end

  private

  def reader_params
    params.require(:reader).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @login = Login.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
Welcome, reader01@email.com

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Libapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="top-menu">
  <%= link_to "Register", register_path %>
</div>

<%= yield %>

</body>
</html>

app/views/readers/new.html.erb
<%= form_for @reader do |f| %>
  <%= f.email_field :email %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Register" %>
<% end %>